### PR TITLE
Fix Issue #33:  Exposing Retry-After value from header in case of 429 HTTP

### PR DESCRIPTION
**Pull request by mathieucarbou**
Tested with `rclone` (see: #33). Value is exposed and rclone is able to wait the correct time before continuing.

See also: https://github.com/ncw/rclone/issues/1788

__IMPORTANT NOTE__: I am not at all a Go developer, so I strongly suggest you review / readapt the code to make it better if needed ;-)

### CODE REVIEW

**Comment by ncw** [comment]
This PR looks sensible to me and fixes a real problem we are having in rclone - what do you think @diwakergupta ?

**Comment by diwakergupta** [comment]
Hey folks, thanks and apologies for the delay here. I haven't looked too closely at the PR yet. One meta comment: @mathieucarbou could you re-work the PR to update the code generator instead of modifying the generated code directly? Thanks!

**Comment by mathieucarbou** [comment]
Hi @diwakergupta : this would take time for me since I am not a Go dev and not used to the template engine you are using. Though, I am ok to spend some time on it, but please give me first some feedback on the PR / code to avoid some back and forth. Thanks!

**Comment by mathieucarbou** [comment]
@diwakergupta : yes, with pleasure 👍

**Comment by ncw** [comment]
@diwakergupta did you push that fix?  I don't see it in the changelog?

Thanks

Nick

**Comment by mathieucarbou** [comment]
@ncw : Dropbox devs are sadly unresponsive. 
The header is there already in HTTP response so this is just a matter of forking their cli and use the forked version in rclone. Anyway, this SDK is not official so whether rclone uses the provided version or its own, it doesn't make any difference in terms of support.

**Comment by diwakergupta** [comment]
@ncw @mathieucarbou sorry about the silence here. I have a patch that does it through code gen, I need to wire up some more tests to make sure I'm handling all the cases correctly (e.g. plain-text vs. JSON responses). I really hope to be able to close this out this week, thanks for your patience!

**Comment by mathieucarbou** [comment]
@diwakergupta @ncw : FYI I had updated my commit, where I have managed to change the templates.
Took me 2 hours.

**Comment by diwakergupta** [comment]
This is resolved in HEAD.

**Comment by diwakergupta** [comment]
> @diwakergupta @ncw : FYI I had updated my commit, where I have managed to change the templates.
> Took me 1 hour.

Alright, now I know who to assign new features to! :)

**Pull request closed without merging**
