### PR TITLE
Added an OAuth2 example and updated the README to link to it.

### PR DESCRIPTION
**Pull request by joncalhoun**

### CODE REVIEW

**Comment by joncalhoun** [comment]
While digging in the source I noticed the `OAuthEndpoint` method which would have helped me avoid the issue I had w/ the wrong url. Hopefully this example can speed up other devs.

**Comment by smarx** [comment]
I don't maintain this library, so it's not really up to me, but I'd be very hesitant to show people sample code like this that doesn't generate a random state parameter and doesn't check its value after the redirect. Without using an unguessable (verified) value for `state`, an app would be wide open to session fixation attacks.

For an example of generating a good `state` parameter, you might want to take a look at my "OAuth the hard way" repo: https://github.com/smarx/othw/blob/master/Go/app.go#L34-L37.

**Comment by joncalhoun** [comment]
My goal in this PR was mostly just to create a barebones example using the RedirectURL as well as the dropbox endpoints, so I stripped pretty much everything out except for what was required to make it work.

I'm not opposed to adding code to show how to properly generate and authenticate a state, but my only concern is that this can creep into other necessary code to make it a complete example. 

eg I believe `rand` is always seeded with `1` if you don't ever call `rand.Seed(value)` (see https://golang.org/pkg/math/rand/#Seed), so arguably if you don't seed it your example is less secure (@smarx I believe your example has this issue, at least assuming I read the rand docs correctly).

As I said, I'm not opposed to adding more code to the example, so if someone lets me know what they think is best I'll update PR to reflect that.

**Comment by lfaraone** [comment]
> so arguably if you don't seed it your example is less secure 

No, because @smarx is using `crypto/rand`, not `math/rand`. The description of the latter states:
> For random numbers suitable for security-sensitive work, see the `crypto/rand` package.

From https://golang.org/pkg/crypto/rand/:
> ```var Reader io.Reader```
> Reader is a global, shared instance of a cryptographically strong pseudo-random generator.
> On Unix-like systems, Reader reads from `/dev/urandom`. On Linux, Reader uses `getrandom(2)` if available, `/dev/urandom` otherwise. On Windows systems, Reader uses the CryptGenRandom API.
[…]
> ```func Read(b []byte) (n int, err error)```
> Read is a helper function that calls `Reader.Read` using `io.ReadFull`. On return, `n == len(b)` if and only if `err == nil`.

**Comment by smarx** [comment]
Yeah, @lfaraone is right. (Phew!)

I understand the desire to make the sample minimal, but the somewhat misnamed `state` parameter is so often not handled properly that I hate to miss an opportunity to show people that they need to generate a random token and have a way to check it.

**Comment by joncalhoun** [comment]
@lfaraone good catch - I didn't realize he was using the crypto package when I glanced at the code.

@smarx sorry for the scare! :(

**Comment by diwakergupta** [comment]
@joncalhoun mind if I close this PR out? Besides the conflicts, I'm not sure if it's still going to be a valuable add.

**Pull request closed without merging**
