### PR TITLE
Fix code generation for unions

### LINKED ISSUE #51: UnmarshalJSON for SaveUrlResult returns an error if the tag is async_job_id
[line 3067 of files/types.go](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/files/types.go#L3067) returns an error because the object cannot be deserialized. Looks like a pretty nasty copy paste bug. I will try to provide a fix

### PR DESCRIPTION
**Pull request by aaronstaley**
Fixes #51.

The Go Generator isn't conforming to the Stone spec for JSON serializing unions. (https://github.com/dropbox/stone/blob/master/docs/json_serializer.rst)

Only struct fields (and structs that are not enumerated subtypes) are mapped straight into the JSON where the parent union tag is.  That was handled correctly.

This fixes primitives not being treated as within a sub-field (which they are supposed to be) as well as structs that are not enumerated subtypes.

In practice, this issue was causing certain responses to fail to deserialize (such as InviteeInfo) in shared file ACLs and was dropping a lot of error fields.

As clean-up, this also stops generating unnecessary fields into wrap.

Tests in a GIST [here](https://gist.github.com/aaronstaley/4230928e187414505be61bcc2b6befbb) (requires latest stone definitions which aren't in push)

### CODE REVIEW

**Comment by diwakergupta** [comment]
@aaronstaley seems like the generated code doesn't compile. Did you check the logs on Travis? e.g. https://travis-ci.org/dropbox/dropbox-sdk-go-unofficial/jobs/595471558

Meanwhile, pinging a few Dropbox folks since I don't have access to this repo anymore.

@dzbarsky @benjaminp @jiuyangzhao @gvanrossum -- hey folks, what's the plan for the Go SDK? If Dropbox isn't planning to maintain it, does it make sense to transfer it to my account? Otherwise I'm happy to fork it for future improvements. LMK.

**Comment by diwakergupta** [comment]
Hmm, most of the folks I tagged don't seem to be in the Dropbox org 🤷‍♂ 

@danielrh @pattyshack could you help route this to the right folks? Thanks!

**Comment by aaronstaley** [comment]
@diwakergupta Ah, we had another bug with handling structs in unions. tl;dr a lot of those is_primitive_type checks should be not _needs_base_type

**Comment by aaronstaley** [comment]
@risforrob actually perhaps this is your job?

**Comment by jiuyangzhao** [comment]
> @aaronstaley seems like the generated code doesn't compile. Did you check the logs on Travis? e.g. https://travis-ci.org/dropbox/dropbox-sdk-go-unofficial/jobs/595471558
> 
> Meanwhile, pinging a few Dropbox folks since I don't have access to this repo anymore.
> 
> @dzbarsky @benjaminp @jiuyangzhao @gvanrossum -- hey folks, what's the plan for the Go SDK? If Dropbox isn't planning to maintain it, does it make sense to transfer it to my account? Otherwise I'm happy to fork it for future improvements. LMK.

Thanks for reminding. I will bring this to API team.

**Comment by aaronstaley** [comment]
@KarandeepJohar Looks like CI might be broken (It couldn't load go 1.1.0?). Can you re-run the job? I may also try doing a single push back from my repo.

**Comment by aaronstaley** [comment]
@risforrob, @jiuyangzhao @KarandeepJohar It's been 2 weeks since this was open. Does Dropbox want to own this SDK or should it be forked?

**Pull request merged**
